version: '3'
services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ../postgres:/var/lib/postgresql/data
